### ISSUE TITLE
what are the commands to get the accuracy

### ISSUE THREAD

**Issue by sachinsourav** [kiking0501/MathDowsers-ARQMath#1]

**Comment by kiking0501** [comment]
For accuracy, are you referring to result evaluation? You might follow the ARQMath official guidelines to get evaluation files and steps.

**Comment by sachinsourav** [comment]
For result evaluation generated by MathDowsers paper 
[ARQMath-1.pdf](https://github.com/kiking0501/MathDowsers-ARQMath/files/9033421/ARQMath-1.pdf)
![Screenshot from 2022-07-02 23-51-40](https://user-images.githubusercontent.com/34065731/177012221-c7523198-9b4b-4ca4-8972-d0c6bed23175.png)

can you suggest how to generate these results for verification it would be helpful.
Thank you

**Comment by kiking0501** [comment]
Unfortunately we did not share the code of Tangent-L (the math retrieval system) publicly, so you cannot re-generate the MathDowsers' runs from scratch. However, our submissions are shared public https://drive.google.com/drive/folders/1KT7ZO9i_cirtI7AfWaPWGDGgpcnXGQhX so you might follow the official guidelines to evaluate them.

**Comment by sachinsourav** [comment]
Ok 
Can i get the official guideline link from where to evaluate by myself.

**Comment by kiking0501** [comment]
Here is the [evaluation directory](https://drive.google.com/drive/folders/1IQDVkBbJO4IhUMSjgs5uDx5KPl0cdEDr). The "Scripts & Qrels" has evaluation scripts for different years.
