### ISSUE TITLE
[Task 7/8 ERROR] prepro_03_create_more_maps.py

### ISSUE THREAD

**Issue by sachinsourav** [kiking0501/MathDowsers-ARQMath#2]
No such file or directory: '/MathARQ/data/ARQMath/prepro_2021/map_raw/creation_year_map.json

This map_raw folder stores the generated raw mappings.

Expected files:

the expected files are not generated after running 6 task 
need a help or solution please.....

**Comment by kiking0501** [comment]
The "creation_year_map" file should be generated if task 5 is successful. Could you check the log to see if the previous tasks are successfully run? Are data created in a correct location?

**Comment by sachinsourav** [comment]
[Task 5/8] Running prepro_01_create_raw_maps_from_parsers.py ...
reading comments
Finish dumping /home/MathARQ/src_2021/data/ARQMath/prepro_2021/map_raw/map_of_comments_for_post.json.
reading post links
Finish dumping /home/MathARQ/src_2021/data/ARQMath/prepro_2021/map_raw/map_related_posts.json.
Finish dumping /home/MathARQ/src_2021/data/ARQMath/prepro_2021/map_raw/map_duplicate_posts.json.
reading votes
Finish dumping /home/MathARQ/src_2021/data/ARQMath/prepro_2021/map_raw/map_of_votes.json.
reading users
Finish dumping /home/MathARQ/src_2021/data/ARQMath/prepro_2021/map_raw/map_of_user.json.
reading posts
Finish dumping /home/MathARQ/src_2021/data/ARQMath/prepro_2021/map_raw/creation_year_map.json.
Finish dumping /home/MathARQ/src_2021/data/ARQMath/prepro_2021/map_raw/map_questions.json.
Finish dumping /home/MathARQ/src_2021/data/ARQMath/prepro_2021/map_raw/map_answers.json.
Finish dumping /home/MathARQ/src_2021/data/ARQMath/prepro_2021/map_raw/map_just_answers.json.
... [Task 5/8] Success!


task 5 was sucessfull 
but 
prepro_2021/map_raw (where generated files should be there is empty)

Any help

**Comment by kiking0501** [comment]
From your log, the generated data is stored under MathARQ/src_2021/data/......, instead of MathARQ/data/....... which is not expected. The design of the data folder path should be the latter, e.g. MathARQ/data/...... 

You might check first to see if there are generated files in MathARQ/src_2021/data/...... . If yes, you might move them back to the expected data folder. Ensure the folder organization is the same as that in this repository and try again,

**Comment by sachinsourav** [comment]
Thanks got it
