### ISSUE TITLE
python3 main_generate_document_corpus.py --style minimal --year all  (have the following error)(please help)

### ISSUE THREAD

**Issue by sachinsourav** [kiking0501/MathDowsers-ARQMath#3]
python3 main_generate_document_corpus.py --style minimal --year all
Succesfully load HTML creator for style [minimal] (keep_latex=False)
Output Folder: /home/MathARQ/data/ARQMath/html_minimal_2021/2010-2018_local
[create_year_htmls] Start:
Year 2010
  0%|                                                                                                        | 0/4563 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/MathARQ/src_2021/main_generate_document_corpus.py", line 476, in <module>
    html_creator.generate_htmls_by_year(year, output_folder=output_folder)
  File "/home/MathARQ/src_2021/main_generate_document_corpus.py", line 385, in generate_htmls_by_year
    output_path = _generate_html_path(
  File "/home/MathARQ/src_2021/main_generate_document_corpus.py", line 349, in _generate_html_path
    folder_path = DATE2FOLDER_MAP[creation_date.year][creation_date.month]
KeyError: 2010

**Comment by kiking0501** [comment]
Your prepro_2021/html-manifest.txt file might have been set to empty. Replace your local copy with [this one](https://github.com/kiking0501/MathDowsers-ARQMath/blob/master/data/ARQMath/prepro_2021/html-manifest.txt).

**Comment by sachinsourav** [comment]
Thanks

**Comment by kiking0501** [comment]
No problem!
